### ISSUE TITLE
Unable to recieve reward for Animal Bundle

### ISSUE THREAD

**Issue by VayeBye** [NinjasCL/stardewvalley-veganmod#2]
Hi. I am running Stardew Valley 1.2 and using your mod. I just completed the Animal Bundle but there is nothing in the rewards box. I now permanently have the reward symbol with nothing to collect.

see image
http://imgur.com/a/LI5hh

**Comment by clsource** [comment]
Thanks for reporting :)

The mod was tested on 1.1
and the 1.2 version have different ids for the items.

So i´m working on an updated version 👍

**Comment by clsource** [comment]
Ok The update is now ready. 
Please test it 👍 Thanks.

https://github.com/NinjasCL/stardewvalley-veganmod/tree/master/1.2
